[package]
name = "pwnpwnd"
version = "0.1.0"
authors = ["Keishi Kawada <Kk-shli@outlook.jp>"]

[dependencies]
futures = "0.1.14"
hyper = "0.11.2"
dotenv = "0.10.1"
envy = "0.3.2"
serde_derive = "1.0"
serde = "1.0"
